# Generated by Django 4.2.16 on 2024-10-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrdName', models.CharField(max_length=100)),
                ('PrdDesc', models.TextField()),
                ('PrdPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('PrdCost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('PrdCreate', models.DateTimeField()),
            ],
        ),
    ]
