# Generated by Django 4.2.16 on 2024-10-13 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PrdCost',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product Cost Price:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PrdCreate',
            field=models.DateTimeField(verbose_name='Product Created At:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PrdDesc',
            field=models.TextField(verbose_name=' Description:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PrdName',
            field=models.CharField(max_length=100, verbose_name='Product Name:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PrdPrice',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product Price:'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDIImage', models.ImageField(upload_to='product/', verbose_name='Image:')),
                ('PRDIProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product:')),
            ],
        ),
    ]
