# Generated by Django 4.2.16 on 2024-10-13 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_alternative_palnalternatives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CATDesc',
            field=models.TextField(verbose_name=' Description :'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATImg',
            field=models.ImageField(upload_to='Category/', verbose_name=' Category Image :'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATName',
            field=models.CharField(max_length=50, verbose_name=' Category Name :'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATParent',
            field=models.ForeignKey(blank=True, limit_choices_to={'CATParent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Main Category :'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PrdCost',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product Cost Price :'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PrdCreate',
            field=models.DateTimeField(verbose_name='Product Created At :'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PrdDesc',
            field=models.TextField(verbose_name=' Description :'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PrdName',
            field=models.CharField(max_length=100, verbose_name='Product Name :'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PrdPrice',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product Price :'),
        ),
        migrations.AlterField(
            model_name='product_accessories',
            name='PACCAlternatives',
            field=models.ManyToManyField(related_name='accessories_product', to='product.product', verbose_name=' Product Accessories :'),
        ),
        migrations.AlterField(
            model_name='product_accessories',
            name='PACCProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessory_Product', to='product.product', verbose_name=' Product Name :'),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='PALNAlternatives',
            field=models.ManyToManyField(related_name='alternative_product', to='product.product', verbose_name=' Product Alternative :'),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='PALNProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_Product', to='product.product', verbose_name=' Product Name :'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='PRDIImage',
            field=models.ImageField(upload_to='product/', verbose_name='Product Image :'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='PRDIProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product Name :'),
        ),
    ]
