# Generated by Django 4.2.16 on 2024-10-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_prdbrand_product_prdcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PrdImage',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Product Image :'),
        ),
    ]
