# Generated by Django 4.2.16 on 2024-10-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_prdimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PrdSlug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
