# Generated by Django 4.2.16 on 2024-10-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_prdslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PrdDiscountPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount Price :'),
            preserve_default=False,
        ),
    ]
