# Generated by Django 4.2.16 on 2024-10-15 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_brand_brddesc_alter_brand_brdname_and_more'),
        ('product', '0012_product_prdbestseller_product_prdisnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CATDesc',
            field=models.TextField(verbose_name='Description:'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATImg',
            field=models.ImageField(upload_to='Category/', verbose_name='Image:'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATName',
            field=models.CharField(max_length=50, verbose_name='Name:'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATParent',
            field=models.ForeignKey(blank=True, limit_choices_to={'CATParent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Main Category:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDBrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.brand', verbose_name='Brand:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PrdBestseller',
            field=models.BooleanField(default=False, verbose_name='Best Seller:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PrdCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Category:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PrdCost',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cost Price:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PrdCreate',
            field=models.DateTimeField(verbose_name='Created At:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PrdDesc',
            field=models.TextField(verbose_name='Description:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PrdDiscountPrice',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount Price:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PrdImage',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Image:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PrdIsNew',
            field=models.BooleanField(default=True, verbose_name='New Product:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PrdName',
            field=models.CharField(max_length=100, verbose_name='Product Name:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PrdPrice',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PrdSlug',
            field=models.SlugField(blank=True, null=True, verbose_name='Product Url:'),
        ),
        migrations.AlterField(
            model_name='product_accessories',
            name='PACCAlternatives',
            field=models.ManyToManyField(related_name='accessories_product', to='product.product', verbose_name='Accessories:'),
        ),
        migrations.AlterField(
            model_name='product_accessories',
            name='PACCProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessory_Product', to='product.product', verbose_name='Product:'),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='PALNAlternatives',
            field=models.ManyToManyField(related_name='alternative_product', to='product.product', verbose_name='Alternative:'),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='PALNProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_Product', to='product.product', verbose_name='Product:'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='PRDIImage',
            field=models.ImageField(upload_to='product/', verbose_name='Image:'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='PRDIProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product:'),
        ),
    ]
