# Generated by Django 4.2.16 on 2024-10-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='BRDDesc',
            field=models.TextField(blank=True, null=True, verbose_name=' Description :'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='BRDName',
            field=models.CharField(max_length=40, verbose_name='Product Brand :'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='VARDesc',
            field=models.TextField(blank=True, null=True, verbose_name=' Description :'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='VARName',
            field=models.CharField(max_length=40, verbose_name='Product Variant :'),
        ),
    ]
